### ISSUE TITLE
Feature request: Triggers for null_resources

### ISSUE THREAD

**Issue by Ghost---Shadow** [oracle-quickstart/oci-postgresql#15]
We should add triggers for `null_resources` so that they run if they change.

https://registry.terraform.io/providers/hashicorp/null/latest/docs/resources/resource

e.g.

```terraform
resource "null_resource" "postgresql_master_install_binaries" {
  triggers = {
    postgresql_master_id = oci_core_instance.postgresql_master.id
  }
...
```

**Comment by lfeldman** [comment]
I am not sure if it is really needed. We have a direct dependency with `depend_on` meta-argument. But let me test your proposal.

**Comment by Ghost---Shadow** [comment]
The trigger makes the script run whenever the value changes. So, whenever the id changes it should run the script again. In my setup I also added the rendered script themselves. So, when they change it triggers it too.

```terraform
triggers = {
    instance_id = oci_core_instance.default.id,
    script1_sh = data.template_file.script1_sh.rendered,
    script2_sh = data.template_file.script2_sh.rendered,
  }
  ```

**Comment by lfeldman** [comment]
I have used your suggestions in the latest release: https://github.com/oracle-quickstart/oci-postgresql/releases/tag/v1.3.1
