### ISSUE TITLE
Feature Request: Attached block volumes

### ISSUE THREAD

**Issue by Ghost---Shadow** [oracle-quickstart/oci-postgresql#18]
A tfvar which creates and uses an attacked block volume instead of the local disk.

**Comment by lfeldman** [comment]
Nice idea! Could you please return with PR?

**Comment by lfeldman** [comment]
@Ghost---Shadow this feature is now available in the latest release: https://github.com/oracle-quickstart/oci-postgresql/releases/tag/v1.3

Closing the issue.
